from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import Response
from sqlalchemy.orm import Session
from app.core.database import get_db
from app.models.finding import Finding, FindingStatus
from app.services.stig_mapper import load_asd_stig, map_finding_to_stig
from lxml import etree
from datetime import datetime
import uuid, re

router = APIRouter()

STATUS_MAP = {
    FindingStatus.open:           "Open",
    FindingStatus.not_a_finding:  "NotAFinding",
    FindingStatus.not_applicable: "Not_Applicable",
    FindingStatus.not_reviewed:   "Not_Reviewed",
}


def _normalize_vuln_id(raw: str) -> str:
    m = re.search(r'V-(\d+)', raw, re.IGNORECASE)
    return f"V-{m.group(1)}" if m else raw


def _build_ckl(findings: list[Finding], project) -> bytes:
    root = etree.Element("CHECKLIST")

    # ASSET block
    asset = etree.SubElement(root, "ASSET")
    for tag, val in [
        ("ROLE", "Application"),
        ("ASSET_TYPE", "Computing"),
        ("HOST_NAME", project.host_name or project.name),
        ("HOST_IP", project.host_ip or ""),
        ("HOST_MAC", ""),
        ("HOST_FQDN", ""),
        ("TECH_AREA", "Application Review"),
        ("TARGET_KEY", ""),
        ("WEB_OR_DATABASE", "false"),
        ("TARGET_COMMENT", project.description or ""),
    ]:
        etree.SubElement(asset, tag).text = val

    # Build vuln_id -> findings index
    finding_index: dict[str, list[Finding]] = {}
    for f in findings:
        vid = f.vuln_id
        if not vid:
            # Try to auto-map on the fly
            match = map_finding_to_stig(f.title or "", f.description or "")
            vids = match.get("vuln_ids", [])
            vid = vids[0] if vids else None
        if vid:
            finding_index.setdefault(vid, []).append(f)

    # STIGS block
    stigs = etree.SubElement(root, "STIGS")
    istig = etree.SubElement(stigs, "iSTIG")

    # STIG_INFO
    stig_info = etree.SubElement(istig, "STIG_INFO")
    stig_data = load_asd_stig()
    for k, v in [
        ("version", "6"),
        ("classification", "UNCLASSIFIED"),
        ("customname", ""),
        ("stigid", "ASD_STIG"),
        ("description", "Application Security and Development Security Technical Implementation Guide"),
        ("filename", "ASD_STIG.xml"),
        ("releaseinfo", f"Generated by RMF Forge {datetime.utcnow().strftime('%Y-%m-%d')}"),
        ("title", "Application Security and Development STIG"),
        ("uuid", str(uuid.uuid4())),
        ("notice", ""),
        ("source", ""),
    ]:
        si = etree.SubElement(stig_info, "SI_DATA")
        etree.SubElement(si, "SID_NAME").text = k
        etree.SubElement(si, "SID_DATA").text = v

    # One VULN block per STIG rule
    # If ASD STIG is loaded, iterate its rules; otherwise use finding_index keys
    if stig_data:
        rule_ids = list(stig_data.keys())
        # Deduplicate — stig_data has both raw and normalized keys
        seen_normalized = set()
        unique_rules = []
        for rid in rule_ids:
            norm = _normalize_vuln_id(rid)
            if norm not in seen_normalized:
                seen_normalized.add(norm)
                unique_rules.append(rid)
    else:
        unique_rules = list(finding_index.keys())

    for raw_vid in unique_rules:
        norm_vid = _normalize_vuln_id(raw_vid)
        rule_info = stig_data.get(raw_vid, stig_data.get(norm_vid, {}))
        mapped_findings = finding_index.get(norm_vid, finding_index.get(raw_vid, []))

        # Determine status
        if not mapped_findings:
            status = "Not_Reviewed"
            finding_details = ""
            comments = ""
            severity = rule_info.get("severity", "medium")
        else:
            # Use worst-case status
            statuses = [f.status for f in mapped_findings]
            if FindingStatus.open in statuses:
                status = "Open"
            elif FindingStatus.not_applicable in statuses:
                status = "Not_Applicable"
            elif FindingStatus.not_a_finding in statuses:
                status = "NotAFinding"
            else:
                status = "Not_Reviewed"

            f = mapped_findings[0]
            severity = f.severity or rule_info.get("severity", "medium")

            # Build finding details — include audit comment and taint trace if present
            detail_parts = [f.title or ""]
            if f.file_path:
                detail_parts.append(f"File: {f.file_path}" + (f" Line: {f.line_number}" if f.line_number else ""))
            if f.taint_trace:
                detail_parts.append(f"Trace: {f.taint_trace}")
            if f.code_snippet:
                detail_parts.append(f"Snippet:\n{f.code_snippet}")
            if f.audit_comment:
                detail_parts.append(f"Developer comment: {f.audit_comment}")
            finding_details = "\n\n".join(filter(None, detail_parts))
            comments = f.justification or ""

        vuln = etree.SubElement(istig, "VULN")
        for sname, sdata in [
            ("Vuln_Num", norm_vid),
            ("Severity", severity.lower() if severity else "medium"),
            ("Group_Title", rule_info.get("title", norm_vid)),
            ("Rule_ID", f"{raw_vid}"),
            ("Rule_Ver", norm_vid),
            ("Rule_Title", rule_info.get("title", "")),
            ("Vuln_Discuss", rule_info.get("description", "")),
            ("Check_Content", ""),
            ("Fix_Text", rule_info.get("fix_text", "")),
            ("CCI_REF", ", ".join(rule_info.get("cci_ids", ["CCI-001310"]))),
        ]:
            sd = etree.SubElement(vuln, "STIG_DATA")
            etree.SubElement(sd, "VULN_ATTRIBUTE").text = sname
            etree.SubElement(sd, "ATTRIBUTE_DATA").text = str(sdata)

        etree.SubElement(vuln, "STATUS").text = status
        etree.SubElement(vuln, "FINDING_DETAILS").text = finding_details
        etree.SubElement(vuln, "COMMENTS").text = comments
        etree.SubElement(vuln, "SEVERITY_OVERRIDE").text = ""
        etree.SubElement(vuln, "SEVERITY_JUSTIFICATION").text = ""

    return etree.tostring(root, pretty_print=True, xml_declaration=True, encoding="UTF-8")


@router.get("/export/{project_id}/ckl")
def export_ckl(project_id: uuid.UUID, db: Session = Depends(get_db)):
    from app.models.project import Project
    project = db.query(Project).filter(Project.id == project_id).first()
    if not project:
        raise HTTPException(404, "Project not found")
    findings = db.query(Finding).filter(Finding.project_id == project_id).all()
    ckl_bytes = _build_ckl(findings, project)
    safe_name = project.name.replace(" ", "_")
    return Response(
        content=ckl_bytes,
        media_type="application/xml",
        headers={"Content-Disposition": f'attachment; filename="{safe_name}.ckl"'},
    )


@router.get("/export/{project_id}/xccdf")
def export_xccdf(project_id: uuid.UUID, db: Session = Depends(get_db)):
    from app.models.project import Project
    project = db.query(Project).filter(Project.id == project_id).first()
    if not project:
        raise HTTPException(404, "Project not found")
    findings = db.query(Finding).filter(Finding.project_id == project_id).all()

    XCCDF_NS = "http://checklists.nist.gov/xccdf/1.1"
    root = etree.Element(f"{{{XCCDF_NS}}}TestResult", nsmap={"xccdf": XCCDF_NS})
    root.set("id", f"xccdf_rmfforge_{uuid.uuid4().hex[:8]}")
    root.set("start-time", datetime.utcnow().isoformat())
    root.set("end-time", datetime.utcnow().isoformat())
    etree.SubElement(root, f"{{{XCCDF_NS}}}title").text = f"RMF Forge — {project.name}"
    bm = etree.SubElement(root, f"{{{XCCDF_NS}}}benchmark")
    bm.set("href", "ASD_STIG.xml")

    for f in findings:
        rr = etree.SubElement(root, f"{{{XCCDF_NS}}}rule-result")
        rr.set("idref", f.vuln_id or "V-222400")
        rr.set("severity", (f.severity or "medium").lower())
        result = etree.SubElement(rr, f"{{{XCCDF_NS}}}result")
        result.text = "fail" if f.status == FindingStatus.open else "pass"
        if f.justification:
            msg = etree.SubElement(rr, f"{{{XCCDF_NS}}}message")
            msg.text = f.justification

    safe_name = project.name.replace(" ", "_")
    return Response(
        content=etree.tostring(root, pretty_print=True, xml_declaration=True, encoding="UTF-8"),
        media_type="application/xml",
        headers={"Content-Disposition": f'attachment; filename="{safe_name}_xccdf.xml"'},
    )


@router.get("/unmapped/{project_id}")
def unmapped_findings(project_id: uuid.UUID, db: Session = Depends(get_db)):
    findings = db.query(Finding).filter(
        Finding.project_id == project_id,
        Finding.vuln_id == None,
    ).all()
    return [{"id": str(f.id), "title": f.title, "source_tool": f.source_tool, "cwe_id": f.cwe_id} for f in findings]
